"""Initial production schema

Revision ID: 4e0a1060238b
Revises: 
Create Date: 2026-08-10 15:10:48.883419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0a1060238b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('location_source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detection_status', sa.String(length=20), nullable=False),
    sa.Column('detection_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_detection_status'), ['detection_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_lng'), ['lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_location_source'), ['location_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('severity_label', sa.String(length=20), nullable=False),
    sa.Column('annotated_image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_damage_type'), ['damage_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_severity_label'), ['severity_label'], unique=False)

    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_messages_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_messages_report_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_messages_created_at'))

    op.drop_table('feedback_messages')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_severity_label'))
        batch_op.drop_index(batch_op.f('ix_detections_report_id'))
        batch_op.drop_index(batch_op.f('ix_detections_damage_type'))

    op.drop_table('detections')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_location_source'))
        batch_op.drop_index(batch_op.f('ix_reports_lng'))
        batch_op.drop_index(batch_op.f('ix_reports_lat'))
        batch_op.drop_index(batch_op.f('ix_reports_detection_status'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    # ### end Alembic commands ###
